import { createApp } from './app.js'
import { config } from './config.js'
import { inject } from '@vercel/analytics'

/**
 * Two-file loader, so the dashboard shows something the moment you clone it.
 *
 *   public/data.json         your own export. Gitignored — it never leaves
 *                            your machine and is never committed.
 *   public/data.sample.json  the synthetic starter set, committed, so a
 *                            fresh clone and the hosted demo both render.
 *
 * Your file wins when it exists. Nothing else in the app knows which one
 * it got, except the banner below.
 */
async function load(path, { required = false } = {}) {
  const res = await fetch(path, { cache: 'no-cache' })
  if (!res.ok) return null

  // A dev server or SPA host answers a missing file with index.html and a 200,
  // so status alone cannot tell you the file exists. Check the type.
  const type = res.headers.get('content-type') || ''
  if (!type.includes('json')) {
    if (required) throw new Error(`${path} is missing (server returned ${type || 'no content-type'})`)
    return null
  }

  try {
    return await res.json()
  } catch {
    if (required) throw new Error(`${path} is not valid JSON`)
    return null
  }
}

function sampleBanner() {
  const el = document.createElement('div')
  el.id = 'sample-banner'
  el.innerHTML =
    `<strong>Demo data.</strong> Every figure, merchant and employer on this page is ` +
    `synthetic — generated by <code>scripts/generate-sample-data.py</code>. ` +
    `Drop your own <code>public/data.json</code> in to replace it.`
  document.body.appendChild(el)
}

// Vercel Web Analytics. Called before the first load so the initial
// pageview is recorded; it patches history.pushState for anything after.
inject()

async function init() {
  const own = await load('/data.json')
  const data = own || (await load('/data.sample.json', { required: true }))
  if (!data) throw new Error('No data.json or data.sample.json found')
  createApp(data)
  document.title = config.documentTitle
  if (!own) sampleBanner()
}

init().catch(err => {
  document.getElementById('app').innerHTML =
    `<div style="color:#f07070;padding:40px;font-family:monospace;">Error loading data: ${err.message}</div>`
})